use tabs to indent. stop using "function ... {"

diff --git a/snap b/snap
--- a/snap
+++ b/snap
@@ -23,8 +23,8 @@ build_info='BUILDINFO'
 spath=$(dirname -- "$(command -v -- "$0")")
 sname="${0##*/}"
 
-function usage {
-    cat <<EOF
+usage() {
+	cat <<EOF
 
 snap options:
 
@@ -81,220 +81,227 @@ snap options:
    NO_X11:true
 
 EOF
-    exit 0
+	exit 0
 }
 
-function get_conf_var {
-    RET=''
-    if [ -e $CONF_FILE ]; then
-	RET=$( grep $1 $CONF_FILE | awk -F : '{if ($1 !~ /^#/) {print $2}}' )
-    fi
+get_conf_var() {
+	RET=''
+	if [ -e $CONF_FILE ]; then
+		RET=$( grep $1 $CONF_FILE | awk -F : '{if ($1 !~ /^#/) {print $2}}' )
+	fi
 
-    if [ "${RET}X" == "X" ]; then
-	return 1
-    else
-	echo $RET
-    fi
+	if [ "${RET}X" == "X" ]; then
+		return 1
+	else
+		echo $RET
+	fi
 }
 
-function msg {
-    if [ $INTERACTIVE == true ]; then
-	echo "${green}${1}${white}"
-    fi
+msg() {
+	if [ $INTERACTIVE == true ]; then
+		echo "${green}${1}${white}"
+	fi
 }
 
-function warn {
-    if [[ $INTERACTIVE == true ]] || [[ $WEXIT == true ]]; then
-	echo "${yellow}${1}${white}"
-	if [ $WEXIT == true ]; then
-	    exit 1
-        fi
-    fi
+warn() {
+	if [[ $INTERACTIVE == true ]] || [[ $WEXIT == true ]]; then
+		echo "${yellow}${1}${white}"
+		if [ $WEXIT == true ]; then
+			exit 1
+		fi
+	fi
 }
 
-function error {
-    if [[ $INTERACTIVE == true ]]; then
-	>&2 echo "${red}${1}${white}"
-    else
-	>&2 echo "${sname}: $1"
-    fi
+error() {
+	if [[ $INTERACTIVE == true ]]; then
+		>&2 echo "${red}${1}${white}"
+	else
+		>&2 echo "${sname}: $1"
+	fi
 
-    if [[ $2 == true ]]; then
-	rollback
-    fi
+	if [[ $2 == true ]]; then
+		rollback
+	fi
 
-    exit 1
+	exit 1
 }
 
-function check_update {
-    if [ "${version}" != "master" ]; then
-	R="https://api.github.com/repos/qbit/snap/releases/latest"
-	LATEST=$(/usr/bin/ftp -o - $R | \
+check_update() {
+	if [ "${version}" != "master" ]; then
+		R="https://api.github.com/repos/qbit/snap/releases/latest"
+		LATEST=$(/usr/bin/ftp -o - $R | \
 			awk -F , '{for(i=1;i<NF;i++){if(match($i, /tag_name/)){print $i}}}' | \
 			cut -d: -f 2 | \
 			tr -d \")
-	rversion=$(echo $LATEST | tr -d \.)
-	lversion=$(echo $version | tr -d \.)
-	if [ $rversion -gt $lversion ]; then
-	    msg "${white}Update ${green}${LATEST}${white} available for ${bold}snap${white}!"
+		rversion=$(echo $LATEST | tr -d \.)
+		lversion=$(echo $version | tr -d \.)
+		if [ $rversion -gt $lversion ]; then
+			msg "${white}Update ${green}${LATEST}${white} available for ${bold}snap${white}!"
 
-	    if [ $INS_UPDATE == true ]; then
-		msg "installing update.."
-		install_update $LATEST
-	    fi
-	else
-	    msg "snap-${version} ${white}is up to date!"
+			if [ $INS_UPDATE == true ]; then
+				msg "installing update.."
+				install_update $LATEST
+			fi
+		else
+			msg "snap-${version} ${white}is up to date!"
+		fi
+		else
+			if [ $INS_UPDATE == true ]; then
+				msg "installing update.."
+				install_update $version
+			fi
 	fi
-    else
-	if [ $INS_UPDATE == true ]; then
-	    msg "installing update.."
-	    install_update $version
-	fi
-    fi
 }
 
-function install_update {
-    sver=$1
-    tmp_file=$(mktemp)
-    /usr/bin/ftp $FTP_OPTS -o "$tmp_file" \
-		 "https://raw.githubusercontent.com/qbit/snap/${sver}/snap"
-    cp "$tmp_file" "$spath/$sname"
-    msg "Installed new version (${sver}) of snap - please re-run!"
-    exit 0
-}
-
-function backup {
-    FAIL=0
-    cp /bsd /obsd || FAIL=1
-    cp /bsd.rd /obsd.rd || FAIL=1
-    cp /sbin/reboot /sbin/oreboot || FAIL=1
-
-    if [ -e /bsd.sp ]; then
-	cp /bsd.sp /obsd.sp || FAIL=1
-    fi
-
-    if [ $FAIL == 1 ]; then
-	error "Failed to backup" false
-    else
-	msg "Backed up the following:
-    ${bold}/bsd => /obsd
-    /bsd.rd => /obsd.rd
-    /sbin/reboot => /sbin/oreboot${green}"
-    fi
-}
-
-function rollback {
-    FAIL=0
-    cp /obsd /bsd || FAIL=1
-    cp /obsd.rd /bsd.rd || FAIL=1
-
-    if [ -e /obsd.sp ]; then
-	cp /obsd.sp /bsd.sp || FAIL=1
-    fi
-
-    cp /sbin/oreboot /sbin/reboot || FAIL=1
-
-    if [ $FAIL == 1 ]; then
-	error "Failed to rollback" false
-    else
-	msg "Restored the old files for the following:
-    ${bold}/bsd => /obsd
-    /bsd.rd => /obsd.rd
-    /sbin/reboot => /sbin/oreboot${green}"
-    fi
-
-}
-
-function check_integ {
-    key=${key:-/etc/signify/snap.pub}
-    file=${sname}
-
-    # signify doesn't like leading ./'s
-    #file=${file:S/\.\///}
-
-    if [ ! -f "${key}" ]; then
-	error "No public key (${key}).\nSee https://github.com/qbit/snap for more info!" false
-    fi
-
-    if [ ! -f "${INTEG_SIG_FILE}" ]; then
+install_update() {
+	sver=$1
 	tmp_file=$(mktemp)
 	/usr/bin/ftp $FTP_OPTS -o "$tmp_file" \
-		     "https://raw.githubusercontent.com/qbit/snap/${version}/SHA256.sig"
-	INTEG_SIG_FILE=${tmp_file}
-    fi
-
-    (
-        # we need to be in the same directory as snap to verify, as that is what
-        # is in SHA256.sig
-        cd $spath && \
-	    signify -C -p "${key}" -x "${INTEG_SIG_FILE}" "${file}"
-    )
+		"https://raw.githubusercontent.com/qbit/snap/${sver}/snap"
+	cp "$tmp_file" "$spath/$sname"
+	msg "Installed new version (${sver}) of snap - please re-run!"
+	exit 0
 }
 
-function verisigs {
-    KEY=/etc/signify/openbsd-${SETVER}-base.pub
-    VALID=true
+backup() {
+	FAIL=0
+	cp /bsd /obsd || FAIL=1
+	cp /bsd.rd /obsd.rd || FAIL=1
+	cp /sbin/reboot /sbin/oreboot || FAIL=1
 
-    if [ -f "$KEY" ]; then
-	for i in "$@"; do
-	    signify -V -e -p ${KEY} -x SHA256.sig -m - | sha256 -C - ${i} \
-		|| VALID=false
-	done
-
-	if [ $VALID == false ]; then
-	    error "Invalid signature found! They are after you!" true
+	if [ -e /bsd.sp ]; then
+		cp /bsd.sp /obsd.sp || FAIL=1
 	fi
-    else
-	error "No pub key found for this release! (${KEY})" false
-    fi
+
+	if [ $FAIL == 1 ]; then
+		error "Failed to backup" false
+	else
+		msg "Backed up the following:
+	${bold}/bsd => /obsd
+	/bsd.rd => /obsd.rd
+	/sbin/reboot => /sbin/oreboot${green}"
+	fi
 }
 
-function update_kernel {
-    FAIL=0
-    if [ $SKIP_SIGN == false ]; then
-	verisigs "bsd*"
-    fi
-    cp ${KERNEL} /bsd || FAIL=1
-    cp ${RD} /bsd.rd || FAIL=1
+rollback() {
+	FAIL=0
+	cp /obsd /bsd || FAIL=1
+	cp /obsd.rd /bsd.rd || FAIL=1
 
-    (umask 077; sha256 /bsd > /var/db/kernel.SHA256)
+	if [ -e /obsd.sp ]; then
+		cp /obsd.sp /bsd.sp || FAIL=1
+	fi
 
-    if [ "${KERNEL}" == "bsd.mp" ]; then
-	cp bsd /bsd.sp || FAIL=1
-    fi
+	cp /sbin/oreboot /sbin/reboot || FAIL=1
 
-    if [ $FAIL == 1 ]; then
-	error "Failed to copy new kernel" false
-    else
-	msg "Set primary kernel to ${KERNEL}:
-    ${KERNEL} => /bsd"
-    fi
+	if [ $FAIL == 1 ]; then
+		error "Failed to rollback" false
+	else
+		msg "Restored the old files for the following:
+	${bold}/bsd => /obsd
+	/bsd.rd => /obsd.rd
+	/sbin/reboot => /sbin/oreboot${green}"
+	fi
+
 }
 
-function fetch {
-    DF=$(echo $1 | awk -F/ '{print $NF}')
-    TDF="${DF}.out"
-    R=0
+check_integ() {
+	key=${key:-/etc/signify/snap.pub}
+	file=${sname}
 
-    # this check may cause signature issues.. if old files exist in
-    # the DEST directory.
-    if [ ! -e $DF ]; then
-	/usr/bin/ftp $FTP_OPTS -o $TDF $1
+	# signify doesn't like leading ./'s
+	#file=${file:S/\.\///}
+
+	if [ ! -f "${key}" ]; then
+		error "No public key (${key}).\nSee https://github.com/qbit/snap for more info!" false
+	fi
+
+	if [ ! -f "${INTEG_SIG_FILE}" ]; then
+		tmp_file=$(mktemp)
+		/usr/bin/ftp $FTP_OPTS -o "$tmp_file" \
+			"https://raw.githubusercontent.com/qbit/snap/${version}/SHA256.sig"
+		INTEG_SIG_FILE=${tmp_file}
+	fi
+
+	(
+		# we need to be in the same directory as snap to verify, as that is what
+		# is in SHA256.sig
+		cd $spath && \
+			signify -C -p "${key}" -x "${INTEG_SIG_FILE}" "${file}"
+	)
+}
+
+verisigs() {
+	KEY=/etc/signify/openbsd-${SETVER}-base.pub
+	VALID=true
+
+	if [ -f "$KEY" ]; then
+		for i in "$@"; do
+			signify -V -e -p ${KEY} -x SHA256.sig -m - | sha256 -C - ${i} \
+				|| VALID=false
+		done
+
+		if [ $VALID == false ]; then
+			error "Invalid signature found! They are after you!" true
+		fi
+	else
+		error "No pub key found for this release! (${KEY})" false
+	fi
+}
+
+update_kernel() {
+	FAIL=0
+	if [ $SKIP_SIGN == false ]; then
+		verisigs "bsd*"
+	fi
+	cp ${KERNEL} /bsd || FAIL=1
+	cp ${RD} /bsd.rd || FAIL=1
+
+	(umask 077; sha256 /bsd > /var/db/kernel.SHA256)
+
+	if [ "${KERNEL}" == "bsd.mp" ]; then
+		cp bsd /bsd.sp || FAIL=1
+	fi
+
+	if [ $FAIL == 1 ]; then
+		error "Failed to copy new kernel" false
+	else
+		msg "Set primary kernel to ${KERNEL}:
+		${KERNEL} => /bsd"
+	fi
+}
+
+fetch() {
+	DF=$(echo $1 | awk -F/ '{print $NF}')
+	TDF="${DF}.out"
+	R=0
+
+	# this check may cause signature issues.. if old files exist in
+	# the DEST directory.
+	if [ ! -e $DF ]; then
+		/usr/bin/ftp $FTP_OPTS -o $TDF $1
 	R=$?
 
 	# move the tmp file to actual file name so we can use -C
 	mv $TDF $DF
-    fi
+	fi
 
-    return $R
+	return $R
 }
 
-function extract {
-    ftp -D Extracting -Vmo - "file://${1}" | tar -C / -xzphf - \
-	|| error "Failed to extract ${1}" false
+extract() {
+	ftp -D Extracting -Vmo - "file://${1}" | tar -C / -xzphf - \
+		|| error "Failed to extract ${1}" false
 }
 
-CONF_FILE=~/.snaprc
+if [ -e ~/.snaprc ]; then
+	CONF_FILE=~/.snaprc
+else
+	if [ -e /etc/snap.conf ]; then
+		CONF_FILE=/etc/snap.conf
+	fi
+fi
+
 SKIP_SIGN=false
 USE_BUILDINFO=true
 CPUS=$(sysctl -n hw.ncpu)
@@ -322,100 +329,100 @@ MIRROR=$(get_conf_var 'MIRROR' || \
 	awk -F/ 'match($3, /[a-z]/) {print $3}' /etc/installurl 2> /dev/null || \
 	echo "cdn.openbsd.org")
 
-while getopts "b:Bc:dD:ehiIkKm:M:nrRsSuUV:wx" arg; do
-    case $arg in
-	b)
-	    INSTBOOT=$OPTARG
-	    ;;
-	B)
-	    NO_KBACKUPS=true
-	    ;;
-	c)
-	    CONF_FILE=$OPTARG
-	    ;;
-	D)
-	    DST=$OPTARG
-	    ;;
-	d)
-	    DOWNLOAD_ONLY=true
-	    ;;
-	e)
-	    EXTRACT_ONLY=true
-	    ;;
-	h)
-	    usage
-	    ;;
-	i)
-	    INTERACTIVE=true
-	    ;;
-	I)
-	    CHK_INTEG=true
-	    shift $((${OPTIND}-1))
-	    INTEG_SIG_FILE=$*
-	    INTEG_SIG_FILE=${INTEG_SIG_FILE:-SHA256.sig}
-	    OPTIND=1
-	    ;;
-	k)
-	    KERNEL_ONLY=true
-	    ;;
-	K)
-	    SETS_ONLY=true
-	    ;;
-	m)
-	    MACHINE=$OPTARG
-	    ;;
-	M)
-	    MIRROR=$OPTARG
-	    ;;
-	n)
-	    FORCE_MP=true
-	    ;;
-	r)
-	    MERGE=true
-	    ;;
-	R)
-	    REBOOT=true
-	    ;;
-	s)
-	    VER='snapshots'
-	    ;;
-	S)
-	    SKIP_SIGN=true
-	    ;;
-	u)
-	    CHK_UPDATE=true
-	    ;;
-	U)
-	    CHK_UPDATE=true
-	    INS_UPDATE=true
-	    ;;
-	V)
-	    SETVER=$(echo $OPTARG | tr -d \.)
-	    ;;
-	W)
-	    WEXIT=true
-	    ;;
-	x)
-	    NO_X11=true
-	    ;;
-	*)
-	    exit 1
-    esac
+while getopts "b:Bc:dD:ehiIkKm:M:nrRsSuUV:Wx" arg; do
+	case $arg in
+		b)
+			INSTBOOT=$OPTARG
+			;;
+		B)
+			NO_KBACKUPS=true
+			;;
+		c)
+			CONF_FILE=$OPTARG
+			;;
+		D)
+			DST=$OPTARG
+			;;
+		d)
+			DOWNLOAD_ONLY=true
+			;;
+		e)
+			EXTRACT_ONLY=true
+			;;
+		h)
+			usage
+			;;
+		i)
+			INTERACTIVE=true
+			;;
+		I)
+			CHK_INTEG=true
+			shift $((${OPTIND}-1))
+			INTEG_SIG_FILE=$*
+			INTEG_SIG_FILE=${INTEG_SIG_FILE:-SHA256.sig}
+			OPTIND=1
+			;;
+		k)
+			KERNEL_ONLY=true
+			;;
+		K)
+			SETS_ONLY=true
+			;;
+		m)
+			MACHINE=$OPTARG
+			;;
+		M)
+			MIRROR=$OPTARG
+			;;
+		n)
+			FORCE_MP=true
+			;;
+		r)
+			MERGE=true
+			;;
+		R)
+			REBOOT=true
+			;;
+		s)
+			VER='snapshots'
+			;;
+		S)
+			SKIP_SIGN=true
+			;;
+		u)
+			CHK_UPDATE=true
+			;;
+		U)
+			CHK_UPDATE=true
+			INS_UPDATE=true
+			;;
+		V)
+			SETVER=$(echo $OPTARG | tr -d \.)
+			;;
+		W)
+			WEXIT=true
+			;;
+		x)
+			NO_X11=true
+			;;
+		*)
+			exit 1
+	esac
 done
 
 if [ $KERNEL_ONLY == true ] && [ $SETS_ONLY == true ]; then
-    echo 'The options -k and -K are mutually exclusive.'
-    exit 1
+	echo 'The options -k and -K are mutually exclusive.'
+	exit 1
 fi
 
 if [ $CHK_INTEG == true ]; then
-    check_integ
-    exit 0
+	check_integ
+	exit 0
 fi
 
 if [ $CHK_UPDATE == true ]; then
-    check_update
-    exit 0
+	check_update
+	exit 0
 fi
 
 [[ $(id -u) -ne 0 ]] && error "need root privileges" false
@@ -423,146 +430,149 @@ fi
 mkdir -p -- "$DST" || exit 1
 
 case "${MIRROR}" in
-    http://* | ftp://* | https://*)
-	URL="${MIRROR}/pub/OpenBSD/${VER}/${MACHINE}"
-	;;
-    *)
-	URL="http://${MIRROR}/pub/OpenBSD/${VER}/${MACHINE}"
-	;;
+	http://* | ftp://* | https://*)
+		URL="${MIRROR}/pub/OpenBSD/${VER}/${MACHINE}"
+		;;
+	*)
+		URL="http://${MIRROR}/pub/OpenBSD/${VER}/${MACHINE}"
+		;;
 esac
 
 if [ ! $EXTRACT_ONLY ]; then
-    msg "${white}Fetching from: ${green}${URL}"
+	msg "${white}Fetching from: ${green}${URL}"
 fi
 
 (
-    cd -- "$DST" || exit 1
+	cd -- "$DST" || exit 1
 
-    # first element should be bsd, second should be mp for given kernel names.
-    if [[ "${MACHINE}" == armv7 ]] || [[ "${MACHINE}" == loongson ]]; then
-	# Currently there is no bsd.mp
-	set -A bsds "bsd" "" "bsd.rd"
-    else
-	set -A bsds 'bsd' 'bsd.mp' 'bsd.rd'
-    fi
-
-    RD=${bsds[2]}
-
-    if [ $SKIP_SIGN == false ]; then
-	fetch "${URL}/${base_sig}" || error "Can't fetch signature file!" false
-    fi
-
-    fetch "${URL}/${build_info}" || USE_BUILDINFO=false
-
-    if [ -e ~/.last_snap ]; then
-	last_snap=$(cat ~/.last_snap)
-	msg "last snap: ${white}${last_snap}"
-	if [ $USE_BUILDINFO ]; then
-	    current_snap=$(awk -F- '{print $2}' "$build_info" | sed 's/^ //')
-	    if [ "${last_snap}" == "$current_snap" ]; then
-		warn "No new snaps available, mirror has: ${current_snap}!"
-	    fi
+	# first element should be bsd, second should be mp for given kernel names.
+	if [[ "${MACHINE}" == armv7 ]] || [[ "${MACHINE}" == loongson ]]; then
+		# Currently there is no bsd.mp
+		set -A bsds "bsd" "" "bsd.rd"
+	else
+		set -A bsds 'bsd' 'bsd.mp' 'bsd.rd'
 	fi
-    fi
 
-    if [ $EXTRACT_ONLY == false ]; then
-        if [ $SETS_ONLY == false ]; then
-            msg "Fetching bsds"
-            for bsd in "${bsds[@]}"; do
-                fetch "${URL}/${bsd}" || error "Can't find bsds at ${URL}" false
-            done
+	RD=${bsds[2]}
 
-            if [ "${CPUS}" == "1" ] && [ "${FORCE_MP:=false}" != true ]; then
-                msg "${white}Using ${green}bsd.."
-                KERNEL=${bsds[0]}
-            else
-                msg "${white}Using ${green}bsd.mp.."
-                KERNEL=${bsds[1]}
-            fi
+	if [ $SKIP_SIGN == false ]; then
+		fetch "${URL}/${base_sig}" || error "Can't fetch signature file!" false
+	fi
 
-            if [ "${NO_KBACKUPS:=false}" == false ]; then
-                if [ $DOWNLOAD_ONLY == false ]; then
-                    backup
-                fi
-            fi
+	fetch "${URL}/${build_info}" || USE_BUILDINFO=false
 
-            if [ $DOWNLOAD_ONLY == false ]; then
-                update_kernel
-            fi
+	if [ -e ~/.last_snap ]; then
+		last_snap=$(cat ~/.last_snap)
+		msg "last snap: ${white}${last_snap}"
+		if [ $USE_BUILDINFO ]; then
+			current_snap=$(awk -F- '{print $2}' "$build_info" | sed 's/^ //')
+			if [ "${last_snap}" == "$current_snap" ]; then
+				warn "No new snaps available, mirror has: ${current_snap}!"
+			fi
+		fi
+	fi
 
-            if [ $KERNEL_ONLY == true ]; then
-                exit 0
-            fi
-        fi # SETS_ONLY
+	if [ $EXTRACT_ONLY == false ]; then
+		if [ $SETS_ONLY == false ]; then
+			msg "Fetching bsds"
+			for bsd in "${bsds[@]}"; do
+				fetch "${URL}/${bsd}" || error "Can't find bsds at ${URL}" false
+			done
 
-	msg "Fetching sets"
+			if [ "${CPUS}" == "1" ] && [ "${FORCE_MP:=false}" != true ]; then
+				msg "${white}Using ${green}bsd.."
+				KERNEL=${bsds[0]}
+			else
+				msg "${white}Using ${green}bsd.mp.."
+				KERNEL=${bsds[1]}
+			fi
+
+			if [ "${NO_KBACKUPS:=false}" == false ]; then
+				if [ $DOWNLOAD_ONLY == false ]; then
+					backup
+				fi
+			fi
+
+			if [ $DOWNLOAD_ONLY == false ]; then
+				update_kernel
+			fi
+
+			if [ $KERNEL_ONLY == true ]; then
+				exit 0
+			fi
+		fi # SETS_ONLY
+
+		msg "Fetching sets"
+		for set in "${sets[@]}"; do
+			fetch "${URL}/${set}${SETVER}.tgz" || \
+				error "Perhaps you need to specify -V to set version. Example 5.2" true
+		done
+
+		if [ "${NO_X11}" == "false" ]; then
+			msg "Fetching xsets"
+			for set in "${xsets[@]}"; do
+				fetch "${URL}/${set}${SETVER}.tgz" || \
+					error "Perhaps you need to specify -V to set version. Example -V 5.2" true
+			done
+		fi
+	fi
+
+	if [ $SKIP_SIGN == false ]; then
+		verisigs "*.tgz"
+	fi
+
+	if [ $DOWNLOAD_ONLY == true ]; then
+		exit 0
+	fi
+
+	msg "Extracting sets"
 	for set in "${sets[@]}"; do
-	    fetch "${URL}/${set}${SETVER}.tgz" || error "Perhaps you need to specify -V to set version. Example 5.2" true
+		extract "${DST}/${set}${SETVER}.tgz"
+
+		if [ "${set}" == "man" ] && [ "${NO_X11}" == "false" ]; then
+			msg "Extracting xsets ${white}will continue with sets after. ${green}"
+
+			for xset in "${xsets[@]}"; do
+				extract "${DST}/${xset}${SETVER}.tgz"
+			done
+		fi
 	done
 
-	if [ "${NO_X11}" == "false" ]; then
-	    msg "Fetching xsets"
-	    for set in "${xsets[@]}"; do
-		fetch "${URL}/${set}${SETVER}.tgz" || error "Perhaps you need to specify -V to set version. Example -V 5.2" true
-	    done
+	if [ $MERGE == true ]; then
+		msg "Running sysmerge"
+		sysmerge || error "Failed to sysmerge!" false
+	else
+		echo "/usr/sbin/sysmerge -b" >>/etc/rc.sysmerge
+		chmod +x /etc/rc.sysmerge
+		echo "Don't forget to run sysmerge!"
 	fi
-    fi
 
-    if [ $SKIP_SIGN == false ]; then
-	verisigs "*.tgz"
-    fi
+	echo -n "Relinking to create unique kernel..."
+	/usr/libexec/reorder_kernel && echo "done." || echo "failed."
 
-    if [ $DOWNLOAD_ONLY == true ]; then
-	exit 0
-    fi
-
-    msg "Extracting sets"
-    for set in "${sets[@]}"; do
-	extract "${DST}/${set}${SETVER}.tgz"
-
-	if [ "${set}" == "man" ] && [ "${NO_X11}" == "false" ]; then
-	    msg "Extracting xsets ${white}will continue with sets after. ${green}"
-
-	    for xset in "${xsets[@]}"; do
-		extract "${DST}/${xset}${SETVER}.tgz"
-	    done
+	if [ $INSTBOOT != false ]; then
+		msg "Installing bootstrap on ${INSTBOOT}"
+		installboot -v $INSTBOOT || \
+			error "Something bad happened - check your boot disk!" false
 	fi
-    done
 
-    if [ $MERGE == true ]; then
-	msg "Running sysmerge"
-	sysmerge || error "Failed to sysmerge!" false
-    else
-	echo "/usr/sbin/sysmerge -b" >>/etc/rc.sysmerge
-	chmod +x /etc/rc.sysmerge
-	echo "Don't forget to run sysmerge!"
-    fi
+	if [ $USE_BUILDINFO ]; then
+		awk -F- '{print $2}' "$build_info" | sed 's/^ //' > ~/.last_snap
+	else
+		date > ~/.last_snap
+	fi
 
-    echo -n "Relinking to create unique kernel..."
-    /usr/libexec/reorder_kernel && echo "done." || echo "failed."
+	if [ "$AFTER" != false ]; then
+		cp $AFTER /etc/rc.firsttime
+		chmod +x /etc/rc.firsttime
+	else
+		echo 'cd /dev && sh MAKEDEV all' >>/etc/rc.firsttime
+		echo "/usr/sbin/fw_update -v" >>/etc/rc.firsttime
+		chmod +x /etc/rc.firsttime
+	fi
 
-    if [ $INSTBOOT != false ]; then
-	msg "Installing bootstrap on ${INSTBOOT}"
-	installboot -v $INSTBOOT || error "Something bad happened - check your boot disk!" false
-    fi
-
-    if [ $USE_BUILDINFO ]; then
-	awk -F- '{print $2}' "$build_info" | sed 's/^ //' > ~/.last_snap
-    else
-	date > ~/.last_snap
-    fi
-
-    if [ "$AFTER" != false ]; then
-	cp $AFTER /etc/rc.firsttime
-	chmod +x /etc/rc.firsttime
-    else
-	echo 'cd /dev && sh MAKEDEV all' >>/etc/rc.firsttime
-	echo "/usr/sbin/fw_update -v" >>/etc/rc.firsttime
-	chmod +x /etc/rc.firsttime
-    fi
-
-    if [ $REBOOT == true ]; then
-	msg "Rebooting"
-	/sbin/oreboot || error "Something really bad happened - Can't reboot!" false
-    fi
+	if [ $REBOOT == true ]; then
+		msg "Rebooting"
+		/sbin/oreboot || error "Something really bad happened - Can't reboot!" false
+	fi
 )
